camel:
  springboot:
      main-run-controller: true

spring:
  activemq:
    broker-url: tcp://localhost:61616
---
spring:
  profiles:
    active: dev

---

spring:
  profiles: dev

activeMQRoute: activemq:writeToMq
fromRoute: file:src/main/resources/input?delete=true
toRoute: file:src/main/resources/output

message: Message from DEV environment.

---
spring:
  profiles: uat

activeMQRoute: activemq:writeToMq
fromRoute: file:src/main/resources/output?delete=true
toRoute: file:src/main/resources/input


message: Message from UAT environment.

---
