camel:
  springboot:
      main-run-controller: true
server:
  port: 9999

spring:
  activemq:
    broker-url: tcp://localhost:61616
    userName: admin
    password: admin
---

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: Reset@123
    driver-class-name: com.mysql.cj.jdbc.Driver

activeMQRoute: activemq:writeToMq
fromRoute: file:src/main/resources/input?delete=true
toRoute: file:src/main/resources/output

message: Message from DEV environment.

---
spring:
  profiles: uat

activeMQRoute: activemq:writeToMq
fromRoute: file:src/main/resources/output?delete=true
toRoute: file:src/main/resources/input


message: Message from UAT environment.

---
